movies/urls.py
from django.urls import path
from . import views



app_name = 'movies'


urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:movie_id>', views.detail, name = 'detail')
]

vidly/urls.py
from django.contrib import admin
from django.urls import path,include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()

urlpatterns = [
    path('',views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/',include(movie_resource.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    #To link Genre and movies list
    genre = models.ForeignKey(Genre,on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse,Http404
from django.shortcuts import render,get_object_or_404
from .models import Movie

# Create your views here.

def index(request):
    movies = Movie.objects.all()
    #output = ', '.join([m.title for m in movies])
    return render(request,'movies/index.html',{'movies' : movies})

def detail(request,movie_id):
    movie = get_object_or_404(Movie,id=movie_id)
    return render(request,'movies/detail.html',{'movie' : movie})
   

vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}

    <dl>
        <dt>Title</dt>
        <dd>{{movie.title}}</dd>
        <dt>Genre</dt>
        <dd>{{movie.genre}}</dd>
        <dt>Stock</dt>
        <dd>{{movie.number_in_stock}}</dd>
    </dl>



{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>

        <tbody>
            {% for movie in movies  %}
            <tr>
                <td>
                <a href ={%url 'movies:detail' movie.id%} >{{movie.title}}</a>
                </td>
                <td>{{movie.genre}}</td>
                <td>{{movie.number_in_stock}}</td>
                <td>{{movie.daily_rate}}</td>
            </tr>
            
            {% endfor %}
            
        </tbody>
    </table>
{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>VIDLY</title>
</head>

<body>

    <nav class="navbar navbar-light bg-light">
         <a class="navbar-brand" href="#">Vidly</a>
    </nav>

    <main class = "container">
        {% block content  %}
        {% endblock  %}

    </main>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

    <a href = "{% url 'movies:index'%}"> Movies</a>


{% endblock %}